# Generated by Django 4.0.4 on 2022-08-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('widget_nr', models.IntegerField()),
            ],
            options={
                'db_table': 'observed_city',
                'managed': False,
            },
        ),
    ]
