# Generated by Django 4.0.4 on 2022-08-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='observedcity',
            table=None,
        ),
    ]
