# Generated by Django 4.0.4 on 2022-08-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_authuser_alter_observedcity_table_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
